name: Linux hardware test

on: [push, pull_request]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@master
    - name: Install necessary tools
      run: |
        rm -rf /etc/apt/trusted.gpg
        sudo apt -y update
        sudo apt -y i2c-tools
    - name: Build it
      run: |
        i2c-detect -y 4
